eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true

server:
    port: 7701

spring:
    application:
        name: DEPARTMENT-SERVICE

    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
        password: secret
        url: jdbc:postgresql://localhost:5433/department
        username: admin

    jpa:
        database: POSTGRESQL
        generate-ddl: true
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: true

    sql:
        init:
            platform: postgres
